export const texts = {
  account: {
    INFO: "Tài khoản của tôi",
    PROFILE: "Hồ sơ",
    ADDRESS: "Địa chỉ",
    REPASS: "Đổi mật khẩu",
    ORDER: "Đơn hàng của tôi",
    NOTIFY: "Thông báo của tôi",
    INFO_MANAGER: "Quản lý hồ sơ",
    NAME_LOGIN: "Tên đăng nhập",
    FULL_NAME: "Họ và tên",
    BIRTHDAY: "Ngày sinh",
    SEX: "Giới tính",
    EMAIL: "Email",
    PHONE_NUMBER: "Số điện thoại",
  },
  list_staff: {
    ALL_STAFF: "Toàn bộ",
    MANAGER: "Quản lý",
    STAFF: "Nhân viên",
  },
  infor_account: {
    STAFF_ID: "Mã nhân viên",
    ACCOUNT_NAME: "Tên tài khoản",
    FULL_NAME: "Họ và tên",
    EMAIL: "Email",
    PHONE_NUMBER: "Điện thoại",
    SEX: "Giới tính",
    PERMISTION: "Chức vụ",
    STATUS: "Trạng thái",
    ACTION: "Thao tác",
    STATUS_ON: "Hoạt động",
    STATUS_BAN: "Khoá",
  },
  common: {
    ALL: "all",
    SORT: "Sắp Xếp Theo",
    DECREASING: "Giá Cao - Thấp",
    ASCENDING: "Giá Thấp - Cao",
    INFORMATION: "Thông tin",
    EDIT: "Sửa",
    DELETE: "Xóa",
    ADD: "Thêm",
    SAVE: "Lưu",
    EXIT: "Thoát",
    NEW: "New",
    DISCOUNT: "Giảm giá",
    TOTAL_AMOUNT: "Tổng tiền",
    PROVISIONAL: "Tạm tính",
    ADD_TO_CART: "Thêm giỏ hàng",
  },
  header: {
    HOME: "Trang chủ",
    PRODUCT: "Sản phẩm",
    LOGIN: "Đăng nhập",
    REGISTER: "Đăng ký",
    ACCOUNT: "Tài khoản",
    LOGOUT: "Đăng xuất",
  },
  product: {
    HOT: "Hot",
    ALL: "Tất cả",
    PRODUCT_NOT_FOUND: "Thông tin sản phẩm không tồn tại!",
    PRODUCT_LIST: "Danh sách sản phẩm",
    NO_PRODUCT: "Không có sản phẩm nào!",
    SOLD_OUT: "Hết hàng",
    OUT_OF_STOCK: "Tạm hết hàng",
    PRODUCT_OTHER: "Sản phẩm khác",
    PRODUCT_NEW: "Sản phẩm mới",
    BEST_SELLER: "Sản phẩm bán chạy nhất",
    AUTHENTIC: "Chính hãng",
    PRODUCT_NAME: "Tên sản phẩm",
    PRODUCT_ID: "Mã sản phẩm",
    MANUFACTURE: "Nhà cung cấp",
    PRICE: "Đơn giá (vnđ)",
    DISCOUNT: "Chiết khấu (%)",
    ORTHER_DISCOUNT: "Chiết khấu khác (%)",
    QUANTITY: "Số lượng nhập",
    REMAINING_QUANTITY: "Số lượng còn lại",
  },
  order: {
    NO_ADDRESS: "Bạn chưa có địa chỉ giao hàng!",
    ACCEPT_ORDER: "Xác nhận và đặt hàng",
    SET_ADDRESS: "Thiết lập địa chỉ",
    ADD_ADRESS: "Thêm địa chỉ mới",
    ADDRESS_SHIP: "Địa chỉ giao hàng",
    TOTAL_PAYMENT: "Tổng tiền thanh toán",
    ORDER_NOW: "Đặt hàng ngay",
    FREE_SHIP: "Miễn phí ship",
    FLAS_SHIP: "Giao hàng nhanh",
  },

  search: {
    RESULTS: "Kết quả tìm kiếm",
    NO_RESULTS: "Không tìm thấy sản phẩm nào",
  },

  errors: {
    DELETE_ACCOUNT_SUCCESS: "Xóa tài khoản thành công!",
    DELETE_ACCOUNT_FAILED: "Xóa tài khoản thất bại!",
    ADD_ACCOUNT_SUCCESS: "Thêm tài khoản thành công!",
    ADD_ACCOUNT_FAILED: "Thêm tài thất bại!",
    EDIT_ACCOUNT_SUCCESS: "Sửa tài khoản thành công!",
    EDIT_ACCOUNT_FAILED: "Sửa tài khoản thất bại!",
    DELETE_PRODUCT_SUCCESS: "Xóa sản phẩm thành công!",
    DELETE_PRODUCT_FAILED: "Xóa sản phẩm thất bại!",
    ADD_PRODUCT_SUCCESS: "Thêm sản phẩm thành công!",
    ADD_PRODUCT_FAILED: "Thêm sản phẩm thất bại!",
    EDIT_PRODUCT_SUCCESS: "Sửa sản phẩm thành công!",
    EDIT_PRODUCT_FAILED: "Sửa sản phẩm thất bại!",
  },
};
